//round จำนวนเต็มที่ใกล้เคียง (เศษตั้งแต่ 0.5 เป็นต้นไปให้ปัดขึ้น)
console.log(Math.round(0.5))
console.log(Math.round(1.40))
console.log(Math.round(1.75))
console.log(Math.round(2.4))
console.log(Math.round(2.5))